kind: Service
apiVersion: v1
metadata:
  labels:
    app: alertmanager
  name: alertmanager
  namespace: prometheus
spec:
  type: NodePort
  ports:
  - port: 9093
    targetPort: 9093
    nodePort: 30007
  selector:
    app: alertmanager
