apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    matrix-application: rabbitmq
    matrix-application-groups: rabbitmq
    matrix-logger: "on"
  name: rabbitmq
  namespace: gpaas
spec:
  replicas: 1
  serviceName: rabbitmq
  selector:
    matchLabels:
      matrix-application: rabbitmq
      matrix-application-groups: rabbitmq
  template:
    metadata:
      labels:
        matrix-application: rabbitmq
        matrix-application-groups: rabbitmq
        matrix-logger: "on"
    spec:
      containers:
      - env:
        - name: K8S_HOST
          value: "kubernetes.default.svc.mce.local"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        - name: RABBITMQ_NODENAME
          value: rabbit@$(MY_POD_IP)
        - name: K8S_SERVICE_NAME
          value: rabbitmq
        - name: RABBITMQ_ERLANG_COOKIE
          value: mycookie
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        - name: AUTOCLUSTER_TYPE
          value: k8s
        - name: AUTOCLUSTER_DELAY
          value: "10"
        - name: K8S_ADDRESS_TYPE
          value: ip
        - name: AUTOCLUSTER_CLEANUP
          value: "true"
        - name: CLEANUP_WARN_ONLY
          value: "false"
        image: pivotalrabbitmq/rabbitmq-autocluster
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1"
        livenessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        name: rabbitmq-autocluster
        ports:
        - containerPort: 15672
          name: http
          protocol: TCP
        - containerPort: 5672
          name: amqp
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /etc/rabbitmq
          name: config-volume
        - mountPath: /var/lib/rabbitmq/mnesia
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: rabbitmq
      serviceAccountName: rabbitmq
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: rabbitmq.conf
            path: rabbitmq.conf
          - key: enabled_plugins
            path: enabled_plugins
          name: rabbitmq-config
        name: config-volume
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      annotations:
        volume.beta.kubernetes.io/storage-class: cloud-ceph
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi