apiVersion: v1
kind: Service
metadata:
  labels:
    matrix-application: rabbitmq
    matrix-application-groups: rabbitmq
  name: rabbitmq
  namespace: gpaas
spec:
  ports:
  - name: http
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: rabbitmq0
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    matrix-application: rabbitmq
    matrix-application-groups: rabbitmq
  sessionAffinity: None
  type: ClusterIP